//! hungarian: [infinitiv, präsems, präteritum, auxiliary, perfekt]
let allwords = {
    // THESE WORDS DO NOT CONTAIN PRäSENS, AND WILL BREAK THE PROGRAM!
    // "elindul": ["abfahren", "fuhr ab", "ist", "abgefahren"],
    // "elrepül": ["abfliegen", "flog ab", "ist", "abgeflogen"],
    // "lead": ["abgeben", "gab ab", "hat", "abgegeben"],
    // "lezár": ["abschließen", "schloss ab", "hat", "abgeschlossen"],
    // "megkínál": ["anbieten", "bot an", "hat", "angeboten"],
    // "elkezd": ["anfangen", "fing an", "hat", "angefangen"],
    // "megérkezik": ["ankommen", "kam an", "ist", "angekommen"],
    // "felhív": ["anrufen", "rief an", "hat", "angerufen"],
    // "megnéz": ["ansehen", "sah an", "hat", "angesehen"],
    // "felvesz": ["anziehen", "zog an", "hat", "angezogen"],
    // "felkel": ["aufstehen", "stand auf", "ist", "aufgestanden"],
    // "kiad, költ": ["ausgeben", "gab aus", "hat", "ausgegeben"],
    // "szórakozni megy": ["ausgehen", "ging aus", "ist", "ausgegangen"],
    // "kinéz vhogyan": ["aussehen", "sah aus", "hat", "ausgesehen"],
    // "kiszáll": ["aussteigen", "stieg aus", "ist", "ausgestiegen"],
    // "elköltözik / levetkőzik": ["ausziehen", "zog aus", "ist/hat", "ausgezogen"],
    // "süt": ["backen", "backte", "hat", "gebacken"],
    // "kezd": ["beginnen", "begann", "hat", "begonnen"],
    // "betart": ["behalten", "behielt", "hat", "behalten"],
    // "kap": ["bekommen", "bekam", "hat", "bekommen"],
    "pályázik": ["bewerben", "bewirbt", "bewarb", "hat", "beworben"],
    "fordul": ["biegen", "biegt", "bog", "hat", "gebogen"],
    "nyújt": ["bieten", "bietet", "bot", "hat", "geboten"],
    "kér": ["bitten", "bittet", "bat", "hat", "gebeten"],
    "marad": ["bleiben", "bleibt", "blieb", "ist", "geblieben"],
    "süt (olajban/zsírban)": ["braten", "brät", "briet", "hat", "gebraten"],
    "tör": ["brechen", "bricht", "brach", "ist", "gebrochen"],
    "ég": ["brennen", "brennt", "brannte", "hat", "gebrannt"],
    "hoz": ["bringen", "bringt", "brachte", "hat", "gebracht"],
    "gondol": ["denken", "denkt", "dachte", "hat", "gedacht"],
    "eszébe jut": ["einfallen", "fällt ein", "fiel ein", "ist", "eingefallen"],
    "meghív": ["einladen", "lädt ein", "lud ein", "hat", "eingeladen"],
    "elalszik": ["einschlafen", "schläft ein", "schlief ein", "ist", "eingeschlafen"],
    "beszáll": ["einsteigen", "steigt ein", "stieg ein", "ist", "eingestiegen"],
    "bevon, behúz": ["einziehen", "zieht ein", "zog ein", "ist", "eingezogen"],
    "ajánl, javasol": ["empfehlen", "empfiehlt", "empfahl", "hat", "empfohlen"],
    "dönt": ["entscheiden", "entscheidet", "entschied", "hat", "entschieden"],
    "eszik": ["essen", "isst", "aß", "hat", "gegessen"],
    "utazik": ["fahren", "fährt", "fuhr", "ist", "gefahren"],
    "(le)esik": ["fallen", "fällt", "fiel", "ist", "gefallen"]
}