//! hungarian: [infinitiv, präsems, präteritum, auxiliary, perfekt]
let allwords = {
    // THESE WORDS DO NOT CONTAIN PRäSENS, AND WILL BREAK THE PROGRAM!
    //* 0-20
    // "elindul": ["abfahren", "fuhr ab", "ist", "abgefahren"],
    // "elrepül": ["abfliegen", "flog ab", "ist", "abgeflogen"],
    // "lead": ["abgeben", "gab ab", "hat", "abgegeben"],
    // "lezár": ["abschließen", "schloss ab", "hat", "abgeschlossen"],
    // "megkínál": ["anbieten", "bot an", "hat", "angeboten"],
    // "elkezd": ["anfangen", "fing an", "hat", "angefangen"],
    // "megérkezik": ["ankommen", "kam an", "ist", "angekommen"],
    // "felhív": ["anrufen", "rief an", "hat", "angerufen"],
    // "megnéz": ["ansehen", "sah an", "hat", "angesehen"],
    // "felvesz": ["anziehen", "zog an", "hat", "angezogen"],
    // "felkel": ["aufstehen", "stand auf", "ist", "aufgestanden"],
    // "kiad, költ": ["ausgeben", "gab aus", "hat", "ausgegeben"],
    // "szórakozni megy": ["ausgehen", "ging aus", "ist", "ausgegangen"],
    // "kinéz vhogyan": ["aussehen", "sah aus", "hat", "ausgesehen"],
    // "kiszáll": ["aussteigen", "stieg aus", "ist", "ausgestiegen"],
    // "elköltözik / levetkőzik": ["ausziehen", "zog aus", "ist/hat", "ausgezogen"],
    // "süt": ["backen", "backte", "hat", "gebacken"],
    // "kezd": ["beginnen", "begann", "hat", "begonnen"],
    // "betart": ["behalten", "behielt", "hat", "behalten"],
    // "kap": ["bekommen", "bekam", "hat", "bekommen"],
    //* 20-40
    // "pályázik": ["bewerben", "bewirbt", "bewarb", "hat", "beworben"],
    // "fordul": ["biegen", "biegt", "bog", "hat", "gebogen"],
    // "nyújt": ["bieten", "bietet", "bot", "hat", "geboten"],
    // "kér": ["bitten", "bittet", "bat", "hat", "gebeten"],
    // "marad": ["bleiben", "bleibt", "blieb", "ist", "geblieben"],
    // "süt (olajban/zsírban)": ["braten", "brät", "briet", "hat", "gebraten"],
    // "tör": ["brechen", "bricht", "brach", "ist", "gebrochen"],
    // "ég": ["brennen", "brennt", "brannte", "hat", "gebrannt"],
    // "hoz": ["bringen", "bringt", "brachte", "hat", "gebracht"],
    // "gondol": ["denken", "denkt", "dachte", "hat", "gedacht"],
    // "eszébe jut": ["einfallen", "fällt ein", "fiel ein", "ist", "eingefallen"],
    // "meghív": ["einladen", "lädt ein", "lud ein", "hat", "eingeladen"],
    // "elalszik": ["einschlafen", "schläft ein", "schlief ein", "ist", "eingeschlafen"],
    // "beszáll": ["einsteigen", "steigt ein", "stieg ein", "ist", "eingestiegen"],
    // "bevon, behúz": ["einziehen", "zieht ein", "zog ein", "ist", "eingezogen"],
    // "ajánl, javasol": ["empfehlen", "empfiehlt", "empfahl", "hat", "empfohlen"],
    // "dönt": ["entscheiden", "entscheidet", "entschied", "hat", "entschieden"],
    // "eszik": ["essen", "isst", "aß", "hat", "gegessen"],
    // "utazik": ["fahren", "fährt", "fuhr", "ist", "gefahren"],
    // "(le)esik": ["fallen", "fällt", "fiel", "ist", "gefallen"],
    //* 40-60
    // "fog": ["fangen", "fängt", "fing", "hat", "gefangen"],
    // "tévét néz": ["fernsehen", "sieht fern", "sah fern", "hat", "ferngesehen"],
    // "talál": ["finden", "findet", "fand", "hat", "gefunden"],
    // "repül": ["fliegen", "fliegt", "flog", "ist", "geflogen"],
    // "ad": ["geben", "gibt", "gab", "hat", "gegeben"],
    // "tetszik": ["gefallen", "gefällt", "gefiel", "hat", "gefallen"],
    // "megy": ["gehen", "geht", "ging", "ist", "gegangen"],
    // "történik": ["geschehen", "geschieht", "geschah", "ist", "geschehen"],
    // "nyer": ["gewinnen", "gewinnt", "gewann", "hat", "gewonnen"],
    // "van vmije, birtokol": ["haben", "hat", "hatte", "hat", "gehabt"],
    // "tart, fog valamit": ["halten", "hält", "hielt", "hat", "gehalten"],
    // "akaszt": ["hängen", "hängt", "hing", "hat", "gehangen"],
    // "nevez, hív": ["heißen", "heißt", "hieß", "hat", "geheißen"],
    // "segít": ["helfen", "hilft", "half", "hat", "geholfen"],
    // "ismer": ["kennen", "kennt", "kannte", "hat", "gekannt"],
    // "cseng": ["klingen", "klingt", "klang", "hat", "geklungen"],
    // "jön": ["kommen", "kommt", "kam", "ist", "gekommen"],
    // "rak": ["laden", "lädt", "lud", "hat", "geladen"],
    // "hagy": ["lassen", "lässt", "ließ", "hat", "gelassen"],
    // "fut": ["laufen", "läuft", "lief", "ist", "gelaufen"]
    //* 60-80
    "sajnál": ["leidtun", "tut leid", "tat leid", "hat", "leidgetan"],
    "kölcsönad": ["leihen", "leiht", "lieh", "hat", "geliehen"],
    "olvas": ["lesen", "liest", "las", "hat", "gelesen"],
    "fekszik": ["liegen", "liegt", "lag", "hat", "gelegen"],
    "elindul (járművel)": ["losfahren", "fährt los", "fuhr los", "ist", "losgefahren"],
    "magával hoz": ["mitbringen", "bringt mit", "brachte mit", "hat", "mitgebracht"],
    "vele jön": ["mitkommen", "kommt mit", "kam mit", "ist", "mitgekommen"],
    "magával visz": ["mitnehmen", "nimmt mit", "nahm mit", "hat", "mitgenommen"],
    "szeret": ["mögen", "mag", "mochte", "hat", "gemocht"],
    "vesz": ["nehmen", "nimmt", "nahm", "hat", "genommen"],
    "nevez": ["nennen", "nennt", "nannte", "hat", "genannt"],
    "tanácsol": ["raten", "rät", "riet", "hat", "geraten"],
    "szagol, szaga van": ["riechen", "riecht", "roch", "hat", "gerochen"],
    "szólít, hív": ["rufen", "ruft", "rief", "hat", "gerufen"],
    "tűnik": ["scheinen", "scheint", "schien", "hat", "geschienen"],
    "alszik": ["schlafen", "schläft", "schlief", "hat", "geschlafen"],
    "üt, ver": ["schlagen", "schlägt", "schlug", "hat", "geschlagen"],
    "zár": ["schließen", "schließt", "schloss", "hat", "geschlossen"],
    "vág": ["schneiden", "schneidet", "schnitt", "hat", "geschnitten"],
    "ír": ["schreiben", "schreibt", "schrieb", "hat", "geschrieben"],
    // 80-100
    // "úszik": ["schwimmen", "schwimmt", "schwamm", "ist", "geschwommen"],
}